apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: horner-reader
  namespace: {{ .Values.namespace }}
spec:
  tls:
    - hosts:
        - horner-reader.{{ .Values.env }}.{{ .Values.hostname }}
      secretName: jerubaal-tls
  ingressClassName: nginx
  rules:
  - host: horner-reader.{{ .Values.env }}.{{ .Values.hostname }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: horner-reader-web-svc
            port:
                number: 80