---
apiVersion: v1
kind: Service
metadata:
  name: horner-reader-api-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: horner-reader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: horner-reader-web-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: horner-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80